[package]
name = "mabe"
edition = "2024"
authors = ["Amon Rayfa <amon@koseka.net>"]
description = "A simple Rust library for creating debug-friendly errors."
repository = "https://github.com/AmonRayfa/mabe"
documentation = "https://mabe.readthedocs.io"
license = "Apache-2.0"
readme = "README.md"
exclude = [
  ".cargo",
  ".env",
  ".github",
  ".gitignore",
  ".trunk",
  "CHANGELOG.md",
  "CONTRIBUTING.md",
  "dist",
  "docs",
  "img",
  "node_modules",
  "package.json",
  "package-lock.json",
  "SECURITY.md",
]
publish = false

[workspace]
members = ["mabe_attr", "mabe_derive"]

[workspace.dependencies]
anyhow = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
terminal_size = "0.4"

[dependencies]
anyhow = { workspace = true }
mabe_attr = { path = "mabe_attr" }
mabe_derive = { path = "mabe_derive", optional = true }
terminal_size = { workspace = true }

[features]
default = ["colorize"]
colorize = []
structured = ["dep:mabe_derive"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
