# Suggestions can sometimes take longer on CI machines, leading to inconsistent results.
suggestionsTimeout: 5000 # ms
version: "0.2"
words:
  [
    amonrayfa,
    androideabi,
    armv,
    clippy,
    consec,
    dunder,
    emscripten,
    getline,
    gnueabi,
    gnueabihf,
    idents,
    koseka,
    mabe,
    markdownlint,
    msvc,
    njsproj,
    nocapture,
    ntvs,
    println,
    rayfa,
    rollup,
    rustup,
    trunkio,
    wasi,
    wasip,
  ]
