# Suggestions can sometimes take longer on CI machines, leading to inconsistent results.
suggestionsTimeout: 5000 # ms
version: "0.2"
words:
  [
    amonrayfa,
    clippy,
    consec,
    dunder,
    idents,
    koseka,
    mabe,
    markdownlint,
    njsproj,
    nocapture,
    ntvs,
    println,
    rayfa,
    rollup,
    trunkio,
  ]
