name: CI/CD

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # Linux
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - i586-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

          # Windows
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu

          # Android
          - aarch64-linux-android
          - arm-linux-androideabi
          - armv7-linux-androideabi
          - i686-linux-android
          - x86_64-linux-android

          # WebAssembly
          - wasm32-unknown-emscripten

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Cross build for ${{ matrix.target }}
        run: cross build --target ${{ matrix.target }} --all-features --verbose

      - name: Cross build for ${{ matrix.target }}
        run: cross build --target ${{ matrix.target }} --release --all-features --verbose

      - name: Cross test for ${{ matrix.target }}
        run: cross test --target ${{ matrix.target }} --all-features --verbose

  cd:
    permissions:
      contents: write

    needs: [ci]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
          RELEASE_TITLE="$(basename "$GITHUB_REPOSITORY") $RELEASE_VERSION"
          RELEASE_NOTES=$(awk '/^## /{i++}i==2{print; while(getline && !/^## /) print; exit}' CHANGELOG.md | tail -n +2)
          gh release create "$RELEASE_VERSION" --title "$RELEASE_TITLE" --notes "$RELEASE_NOTES"
