name: CI/CD

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build for development
        run: cargo build --all-features --verbose

      - name: Build for release
        run: cargo build --release --all-features --verbose

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --all-features --verbose

  release:
    permissions:
      contents: write

    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Extract release notes
        run: |
          RELEASE_NOTES=$(awk '/^## /{i++}i==2{print; while(getline && !/^## /) print; exit}' CHANGELOG.md | tail -n +3 | head -n -1)
          echo "$RELEASE_NOTES" > release_notes.md
          echo "::set-output name=notes::$(cat release_notes.md)"

      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${GITHUB_REF#refs/tags/}" --title "mabe ${GITHUB_REF#refs/tags/}" --notes ""
